name: clang-tidy (static analysis)
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
      # we need to generate a special file "compile_commands.json"
      # to do this, we need to run cmake with the following options:
      # -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      # I'm fairly sure that we don't need to run the actual build,
      # but it's not obvious to me how to do this. So, I'm just going 
      # to run a full build for now, and we can FIXME this later.
      - name: Prequisites for build
        run: |
          bash .github/workflows/scripts_new/clang_tidy/1_prerequisites.sh
      - name: Build
        run: |
          bash .github/workflows/scripts_new/clang_tidy/2_build.sh
      - name: Clang-tidy
        run: |
          bash .github/workflows/scripts_new/clang_tidy/3_test.sh
