name: Manual workflow
on:
  workflow_dispatch:
jobs:
  echo-hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Echo Hello
        run: |
          echo "Hello, world!"
          pwd
          uname -a
          free -m
          cat /etc/lsb-release
          ls -la
          python -V
          ./build.py --shell
