name: Linux x86
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Linux x86 Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Linux x86 prerequisites
        run: |
          bash .github/workflows/scripts_new/linux_x86/1_prerequisites.sh
      - name: Linux x86 build
        run: |
          bash .github/workflows/scripts_new/linux_x86/2_build.sh
      - name: Linux x86 install
        run: |
          bash .github/workflows/scripts_new/linux_x86/3_install.sh
      - name: Linux x86 test
        run: |
          bash .github/workflows/scripts_new/linux_x86/4_test.sh
